### ISSUE TITLE
No effect. Library still working?

### ISSUE THREAD

**Issue by mlostekk** [TheAmazingAudioEngine/RealtimeWatchdog#6]
We are using this library to monitor our audio thread. Now by accident i did something really nasty. I am using RxSwift inside the audio thread. RxSwift uses `Foundation.NSRecursiveLock` for each publishing. With this introduced we should see some warnings in the console. but it stays clean

Now i am wondering if this library is still working? Is it compatible with swift5? xcode 10.3?

**Comment by michaeltyson** [comment]
Hi! Yeah it should be working - but it's only looking for stuff I've told it to look for, it can't catch everything. We'll need to work out what NSRecursiveLock uses and add that to the checks probably. It's probably open source so that should be doable

**Comment by mlostekk** [comment]
Oh okay. But it should find out regular c mallocs right?

**Comment by michaeltyson** [comment]
Yeah it should definitely do that

**Comment by michaeltyson** [comment]
It's interesting; as far as I can tell, NSRecursiveLock just uses pthread_mutex, but some optimisation is being applied which bypasses the actual pthread_mutex_lock call, which is the one that this utility catches. It's going straight to internal calls, and I can't find any but the lowest-level one (_psynch_mutexwait, which is only called when there's contention). So, not sure how to actually detect this one, besides just overloading -[NSRecursiveLock lock] itself.

#0	0x00000001081dcf06 in __psynch_mutexwait ()
#1	0x0000000108231d52 in _pthread_mutex_firstfit_lock_wait ()
#2	0x000000010822f4cd in _pthread_mutex_firstfit_lock_slow ()
#3	0x00000001056163c8 in -[NSRecursiveLock lock] ()
